version: "3.3"

services:

  database:
    build:
      context: .
      dockerfile: build/db.Dockerfile
    ports: 
      - 5000:5432

  main:
    depends_on: 
      - database
    build:
      context: .
      dockerfile: build/main.Dockerfile
    ports:
      - 8081:8081

  prometheus:
    image: prom/prometheus
    depends_on: 
      - main
    ports:
      - 9090:9090
      - 9100:9100
    volumes:
      - "./build/prometheus:/etc/prometheus"
    logging: 
      driver: none

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    logging: 
      driver: none