version: "3.3"

# networks:
#   credentials_network:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: "169.254.170.0/24"

services:

  # ecs-local-endpoints:
  #   image: amazon/amazon-ecs-local-container-endpoints
  #   volumes:
  #     - /var/run:/var/run
  #     - ./.aws/:/home/.aws/
  #   networks:
  #     credentials_network:
  #       ipv4_address: "169.254.170.2"

  database:
    build:
      context: .
      dockerfile: build/db.Dockerfile
    # networks:
    #   credentials_network:
    #     ipv4_address: "169.254.170.4"

  tarantool:
    build:
      context: .
      dockerfile: build/tarantool.Dockerfile
    # networks:
    #   credentials_network:
    #     ipv4_address: "169.254.170.5"

  main:
    depends_on: 
      - database
      - tarantool
    #   - ecs-local-endpoints
    # networks:
    #   credentials_network:
    #     ipv4_address: "169.254.170.3"
    build:
      context: .
      dockerfile: build/main.Dockerfile
    ports:
      - 8081:8081
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./static/:/app/static/:rw

  prometheus:
    image: prom/prometheus
    depends_on: 
      - main
      - node-exporter
    volumes:
      - ./build/prometheus:/etc/prometheus
    ports:
      - 9090:9090
    logging: 
      driver: none

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    logging: 
      driver: none

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - node-exporter
    ports:
      - 4000:3000
    volumes:
      - grafana-storage:/var/lib/grafana/:rw
    logging: 
      driver: none

volumes:
  grafana-storage:
