// Code generated by MockGen. DO NOT EDIT.
// Source: Redioteka/internal/pkg/domain (interfaces: ActorUsecase)

// Package mock is a generated GoMock package.
package mock

import (
	domain "Redioteka/internal/pkg/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockActorUsecase is a mock of ActorUsecase interface.
type MockActorUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockActorUsecaseMockRecorder
}

// MockActorUsecaseMockRecorder is the mock recorder for MockActorUsecase.
type MockActorUsecaseMockRecorder struct {
	mock *MockActorUsecase
}

// NewMockActorUsecase creates a new mock instance.
func NewMockActorUsecase(ctrl *gomock.Controller) *MockActorUsecase {
	mock := &MockActorUsecase{ctrl: ctrl}
	mock.recorder = &MockActorUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorUsecase) EXPECT() *MockActorUsecaseMockRecorder {
	return m.recorder
}

// GetById mocks base method.
func (m *MockActorUsecase) GetById(arg0 uint) (domain.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0)
	ret0, _ := ret[0].(domain.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockActorUsecaseMockRecorder) GetById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockActorUsecase)(nil).GetById), arg0)
}

// Search mocks base method.
func (m *MockActorUsecase) Search(arg0 string) ([]domain.Actor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0)
	ret0, _ := ret[0].([]domain.Actor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockActorUsecaseMockRecorder) Search(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockActorUsecase)(nil).Search), arg0)
}
